version: "3.7"
services:

  dbt:
    image: python:3.8.5
    environment:
      - GOOGLE_CLOUD_PROJECT
    entrypoint: "/repo/run_test.sh ${TARGET}"
    working_dir: /repo
    volumes:
        - ".:/repo"
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpass