integration_tests:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: "{{ env_var('BIGQUERY_AUTH_METHOD') }}"
      project: "{{ env_var('BIGQUERY_TEST_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_TEST_DATASET') }}"
      threads: 1